UPDATE userinfo
SET NAME = 'Vian'
WHERE USERNAME = 'vian';
CREATE DATABASE user_system;

CREATE TABLE USERINFO (
    ID INT(5) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(30),
    NAME VARCHAR(30),
    EMAIL VARCHAR(30),
    ADDRESS VARCHAR(50),
    PASSWORD VARCHAR(255)
);


CREATE TABLE INVENTORY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	ITEM_NAME VARCHAR(100),
	QUANTITY INT,
	DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (USER_ID) REFERENCES USERINFO(ID)
);
CREATE TABLE inventory (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_name VARCHAR(100),
  quantity INT
);

